backend:
  name: git-gateway
  branch: main
media_folder: 'assets/uploads'
collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages' # Used in the UI
    folder: 'pages' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          time_format: false,
          date_format: 'YYYY-MM-DD',
          format: 'YYYY-MM-DD',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
