backend:
  name: git-gateway
  branch: main
media_folder: '/_tmp/uploads'
public_folder: '/assets/uploads'
site_url: https://locene.netlify.app
display_url: https://locene.netlify.app
collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages' # Used in the UI
    label_singular: 'Page'
    folder: 'src' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'base.liquid' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          time_format: false,
          date_format: 'YYYY-MM-DD',
          format: 'YYYY-MM-DD',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Links'
        label_singular: 'Link'
        name: 'links'
        widget: 'list'
        summary: '{{fields.title}} - {{fields.url}}'
        fields:
          - { label: URL, name: url, widget: string, default: 'https://google.com' }
          - { label: Title, name: title, widget: string, default: 'Google' }
